services:
  flask:
    build: ./
    restart: always
    ports:
      - '$FLASK_PORT:5000'
    environment:
      - SQL_HOST
      - SQL_PORT
      - SQL_DRIVER
      - SQL_DB
      - FLASK_PORT
      - SESSION_LIFETIME_MINUTES
    volumes:
      - /app/venv
      - ./:/app